### ISSUE TITLE
New :use_tls option for start_tls() (for choosing TLS or SSL)

### ISSUE THREAD

**Issue by ibc** [eventmachine/eventmachine#359]
Hi, eventmachine uses SSLv23 when start_tls() is used. This means that there is no way to tell EM to use TLSv1.

I've added a new option `:use_tls` for the `start_tls()` method which lets the user to choose TLS (by setting it to true) instead of SSL. It's tested and works.

It's implemented in EventMachine-LE:

https://github.com/ibc/EventMachine-LE/commit/98296183f206d7a8f1472ac2ac5f4438ae82c6e5

(of course I do know that this GOOD suggestion will be totally ignored by EM developers).

**Comment by sodabrew** [comment]
Closing in favor of PR #570

**Comment by archSeer** [comment]
@sodabrew I don't think this should be closed. #570 addresses the original issue, but does not address the concerns I had.

**Comment by sodabrew** [comment]
Ok, I re-read some of the linked issues, and the changes in eventmachine-le aren't necessarily a final resolution to all of the concerns. Reopening, will need to come back to this and do some more work.

@archSeer I think your suggestion of the enable / disable option list is the best one.

In particular, SSL is basically dead now, since BEAST and POODLE. So we'll need something like this:

Apache
```
SSLProtocol All -SSLv2 -SSLv3

```

nginx
```
ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
```

**Comment by fabiokung** [comment]
> @archSeer I think your suggestion of the enable / disable option list is the best one.

@sodabrew #438

**Comment by sodabrew** [comment]
Thanks @fabiokung I will follow up on your PR!

**Comment by sodabrew** [comment]
Superseded by #654
