### ISSUE TITLE
How can i close a socket ?

### ISSUE THREAD

**Issue by humbass** [eventmachine/eventmachine#458]
socket client is closed, but server(with eventmachine) is still alive:

1,   server still puts  @num+1
2,   window7 cmd line, type    netstat -an | find "8888" && echo
      more listen thread at port 8888

 TCP    192.168.0.251:4768     192.168.0.251:8888     TIME_WAIT
 TCP    192.168.0.251:4769     192.168.0.251:8888     TIME_WAIT
 TCP    192.168.0.251:4770     192.168.0.251:8888     TIME_WAIT
 TCP    192.168.0.251:4772    192.168.0.251:8888     TIME_WAIT
 TCP    192.168.0.251:4777     192.168.0.251:8888     TIME_WAIT

  how can i close the socket completely when client is closed?

Code such as the following:
#----------- ------------------------------------------------------
require 'rubygems'
require 'eventmachine'
class Test < EventMachine::Connection

    def post_init
        @num = 0  
    end   
    def receive_data(data)
    puts data
    send_data "send_response\n"
        EventMachine::add_periodic_timer(1){
            puts (@num += 1)
        }
    end
    def unbind
        puts "-- #user disconnected from the echo server!" 
        close_connection_after_writing
    end  
end

EventMachine::run do
    EventMachine::start_server "0.0.0.0", 8888, Test
    Signal.trap("INT")  { EventMachine.stop }
    puts "test server listen ..."
end
#----------------------------------------------------------------------

**Comment by sodabrew** [comment]
Apologies for the delayed reply.

You did close the connection. That's why it's in TIME_WAIT state.
http://en.wikipedia.org/wiki/Transmission_Control_Protocol#Protocol_operation
> TIME-WAIT 
(either server or client) represents waiting for enough time to pass to be sure the remote TCP received the acknowledgment of its connection termination request. [According to RFC 793 a connection can stay in TIME-WAIT for a maximum of four minutes known as a MSL (maximum segment lifetime).]

**Comment by humbass** [comment]
@sodabrew Thank you, I have found the way.
