### ISSUE TITLE
When using epoll, `stop_event_loop` doesn't take effect until the next timer fires

### ISSUE THREAD

**Issue by piki** [eventmachine/eventmachine#522]
When eventmachine is using `EM.epoll` and has at least one timer set up, a call to `stop_event_loop` will have no effect until the next timer fires.

For example, this program takes up to five seconds to exit when it gets a SIGTERM.  If there aren't any timers, the program exits after about 90ms, the value of `Quantum.tv_usec`.  If the `EM.epoll` line is commented out, the program exits immediately, whether or not any timers are scheduled.

```
EM.epoll
EM.run {
  EM.add_periodic_timer(5) do
    puts "timer"
  end
  EM.add_shutdown_hook do
    puts "shutting down: #{Time.now.to_f}"
  end
  Signal.trap("TERM") do
    puts "SIGTERM: #{Time.now.to_f}"
    EM::stop_event_loop
  end
}
```

Does the epoll version of `stop` need to signal the loop breaker?

**Comment by sodabrew** [comment]
The typical way to stop is `EM.stop` rather than `EM::stop_event_loop`. Would that resolve the issue here?

**Comment by piki** [comment]
Nope.  The program still doesn't exit until the next timer fires, even with `EM::stop` (or `EM.stop`) instead of `EM::stop_event_loop`.

Note that the problem only happens on Linux, since only Linux has `epoll`.

**Comment by tmm1** [comment]
Signaling the loopbreaker on stop makes sense, but I'm not sure offhand if it would cause problems elsewhere.

``` diff
diff --git a/ext/em.cpp b/ext/em.cpp
index b911d92..8bb63ef 100644
--- a/ext/em.cpp
+++ b/ext/em.cpp
@@ -192,6 +192,7 @@ void EventMachine_t::ScheduleHalt()
    * The answer is to call evma_stop_machine, which calls here, from a SIGINT handler.
    */
        bTerminateSignalReceived = true;
+       SignalLoopBreaker();
 }

```

**Comment by piki** [comment]
There may be an easier way to fix this that doesn't involve the loop breaker.  (The loop breaker may be worth avoiding, because it calls Ruby callbacks rather than just stopping EM.)

The underlying problem is that `rb_wait_for_single_fd` (used [here](https://github.com/eventmachine/eventmachine/blob/master/ext/em.cpp#L577)) retries its `ppoll` call on any `EINTR`.  So the process gets SIGTERM or SIGINT, calls `EM.stop`, sets `bTerminateSignalReceived`, and then retries `ppoll` with the original timeout anyway.  If we skip the `rb_wait_for_single_fd` call and just go straight to `epoll_wait` -- which doesn't retry after `EINTR` -- everything appears to work.  It's as simple as removing the entire `#ifdef BUILD_FOR_RUBY` block [here](https://github.com/eventmachine/eventmachine/blob/master/ext/em.cpp#L573-L601).

@tmm1, it appears you wrote the `BUILD_FOR_RUBY` block.  I'm not sure what that `#define` means.  What's [the block](https://github.com/eventmachine/eventmachine/blob/master/ext/em.cpp#L573-L601) there for, and can we just remove it?

**Comment by tmm1** [comment]
BUILD_FOR_RUBY is because it used to be possible to build the reactor as a c/c++ library for use without ruby.

In early versions of EM we would call epoll directly. However this broke ctrl+c (https://github.com/macournoyer/thin/issues/51) because the ruby vm was never notified of the incoming signals. For a while we surrounded the epoll with calls to the `TRAP_BEG` and `TRAP_END` macros which solved the issue in ruby 1.8. But those were internal macros which disappeared in newer releases, so we switched to `rb_thread_select` on the epoll fd which ensured the same macros was invoked internally by the VM around its invocation of select(). When that function was deprecated, we switched to `rb_wait_for_single_fd`.

> It's as simple as removing the entire #ifdef BUILD_FOR_RUBY block here.

This won't work because it means the entire ruby VM (i.e. all ruby threads sitting behind the GVL) will block until epoll_wait returns. By using `rb_wait_for_single_fd` on the epoll fd instead, we allow the VM to unblock other threads that might have i/o waiting.

**Comment by matheussilvasantos** [comment]
It doesn't stop in the latest master if we want to call stop inside `add_timer` so we can stop inside an untrapped environment.

If I launch this script and hit Ctrl+C after it starts, I have to wait 30 seconds:

```ruby
EM.run do
  puts "EM has just started."

  EM.add_periodic_timer(30) do
    puts "hello friend, hello friend"
  end

  Signal.trap("INT") do
    EM.add_timer(0) do
      EM.stop
    end
  end

  Signal.trap("TERM") do
    EM.add_timer(0) do
      EM.stop
    end
  end
end
```

**Comment by matheussilvasantos** [comment]
Calling `EM::signal_loopbreak` before `EM.add_timer(0)` makes the script work.
It doesn't work if I place it inside `EM.add_timer(0)` - probably because it never enters it before executing the periodic timer.
