### ISSUE TITLE
what():  no allocation for outbound data

### ISSUE THREAD

**Issue by CirrusThink** [eventmachine/eventmachine#641]
I am getting these errors that so far are pointing to eventmachine, but not sure how to move forward from here 
terminate called after throwing an instance of 'std::runtime_error'
 what():  no allocation for outbound data

**Comment by sodabrew** [comment]
Do you have more of a backtrace available? Could you list the operating system, Ruby, and eventmachine versions at play?

**Comment by tmm1** [comment]
These errors are thrown when `malloc` fails to allocate memory: https://github.com/eventmachine/eventmachine/blob/b3bfe235c8a0283b2ee8b8bdc4e97f91f62fdfc1/ext/ed.cpp#L648-L650

**Comment by sodabrew** [comment]
Closing this since it can't really be fixed; maybe you can send data in smaller chunks or wait between chunks so that less outbound data needs to be held in memory at a given time?

**Comment by alexdowad** [comment]
> Closing this since it can't really be fixed...

Idea: If you can't allocate a needed buffer, then stop processing the request which needed the buffer, free all the other memory it may be using, log an error, drop the TCP connection, then go back to your main loop.

Crashing someone's app because one response used a lot of memory is not cool. Of course, if this happens many times in a row, it may be better to give up.
