### ISSUE TITLE
Encryption not available on this machine. eventmachine-1.2.7

### ISSUE THREAD

**Issue by milteven12** [eventmachine/eventmachine#872]
Hello, I'm trying to run the code: 
```
require 'faye/websocket'
require 'eventmachine'

data = []
count = 0

EM.run {
ws = Faye::WebSocket::Client.new('wss://olymptrade.com/ds/v3')


ws.on :open do |event|
p [:open]
ws.send('{"uuid":"JCBQ7XBRMYSL0JB4N5","pair":"Bitcoin","size":60}')
end

ws.on :message do |event|
p [:message, event.data]
    data << event.data
    data_servertime = data[0].gsub(/[^\d]/, '').to_i
    data.delete_at(0)

    if ((data_servertime % 15) == 0)
        puts "15"
    elsif ((data_servertime % 60) == 0)
        puts "60"
    end
end

ws.on :close do |event|
p [:close, event.code, event.reason]

ws = nil
end

}
```
But the console is throwing an error: `Encryption not available on this machine.`

* eventmachine-1.2.7
* OpenSSL 1.1.1
* Windows 10

**Comment by MSP-Greg** [comment]
@milteven12

Can you provide the output of:
```
ruby -reventmachine -ve "puts EM.library_type, EM.ssl?"
```

**Comment by milteven12** [comment]
@MSP-Greg 

Output:

ruby 2.5.3p105 (2018-10-18 revision 65156) [x64-mingw32]
extension
false

I have both versions installed.

**Comment by milteven12** [comment]
Hello @MSP-Greg , I didn't remembered if it was installed or not but I downloaded the OpenSLL-Win64 v1.1.0j and Installed, after that, I uninstalled both of the eventmachine and installed the eventmachine-1.0.8 but it still gives me the same error.

Should I uninstall everything and retry?
There is a ruby command to automatically install the same version of your fork?

Thank you.

**Comment by MSP-Greg** [comment]
Ok.  FYI, unless you need it for other software, OpenSLL-Win64 can cause issues with Ruby installs.

> Should I uninstall everything and retry?

Certainly not everything.  Since your system seems to be compiling EM, maybe uninstall all versions of Eventmachine with `gem uninstall eventmachine`...

> There is a ruby command to automatically install the same version of your fork?

Yes.  First download:
https://ci.appveyor.com/api/buildjobs/yesf8k8ntb260g7b/artifacts/eventmachine-1.3.0.dev.1-x64-mingw32.gem

Then, run `gem install -l <full path to file>`, and it should install.  It's compatible with Ruby 2.0 thru 2.6, and uses OpenSSL 1.1.1 for Ruby 2.5 and greater.

**Comment by milteven12** [comment]
Thank You, it is solved.

**Comment by MSP-Greg** [comment]
@milteven12 

Good.  Did you use `eventmachine-1.3.0.dev.1-x64-mingw32.gem` or re-compile `eventmachine-1.2.7`?

**Comment by milteven12** [comment]
` eventmachine-1.3.0.dev.1-x64-mingw32.gem`
