### ISSUE TITLE
Next release - remove support for old Rubies?

### ISSUE THREAD

**Issue by MSP-Greg** [eventmachine/eventmachine#997]
EM currently supports Ruby 2.0 with the following in the gemspec `s.required_ruby_version = '>= 2.0.0'`.

CI is testing starting with Ruby 2.3.

Is it time to set the minimum Ruby version to 2.5 or greater?

**Comment by nevans** [comment]
Short answer:  _Yes._  Let's drop everything below 2.5 from CI and update the gemspec to require `>= 2.5.0`.

Longer rambling answer:

In my estimation, EventMachine is currently primarily used by older legacy applications.  And in my opinion, greenfield ruby projects should (and will) probably choose to use async or polyphony over eventmachine.  Since eventmachine is primarily used on older projects, there _is_ benefit to maintaining _some_ level of support for older ruby versions.  On the other hand, the changes to OpenSSL are significant.  And maintaining support for both newer and older ruby versions has non-trivial costs too--especially taking changes to ruby's C extension API into account.

I personally think that we should treat "development platforms" and "deployment platforms" differently.  I would consider windows and macos to be "development" and only Linux as fully supported for deployment.  Currently, I'd categorize "pure ruby" mode as a "development platform" too.  And JRuby... doesn't even have a running build at the moment (not to mention TruffleRuby, etc).  (Longer term, I'd like to gradually move more functionality into "pure ruby" mode, to simplify keeping up with openssl and potentially provide an upgrade path for migrating application code into using Fiber Scheduler, but that's out of scope for this issue!)

Practically speaking, GitHub Action's supported Linux runners are all Ubuntu LTS releases: ubuntu-20.04, ubuntu-22.04, ubuntu-24.04.

For the different platforms:
* **Development platforms:**  Strictly drop CI support for any EOL ruby, as soon as it is EOL.
* **Deployment platforms:**  Continue to support (in the gemspec and in CI) the most recent _four_ (4) EOL ruby versions: 
  * IMO, we are justified in excluding versions of ruby that were already EOL when that version of Ubuntu was released: so ubuntu-22.04 would only use ruby 2.6+, ubuntu 24.04 would only use ruby 3.0+, etc.

In other words, currently:
* Four most recent EOL ruby versions: `2.5`, `2.6`, `2.7`, `3.0`
  * These should be supported by the gemfile and CI `ubuntu` runners
  * CI builds for Window, MacOS, and pure ruby should _not_ test these.
* Three current ruby versions: `3.1`, `3.2`, `3.3`
  _(note that there are_ **four** _current ruby versions for three months every year, between Dec 25 and ~Mar 31)_
* One `head` version
  * These should run on all platforms, but shouldn't be required to pass for merging PRs.

Why four EOL versions and not two or some other number?  In order of importance, highest to lowest:
* It matches what you suggested: 2.5+
* It has a nice symmetry: four EOL + four current/dev  😉
* Assuming that GitHub Actions drops Ubuntu LTS runners shortly before the Ubuntu Maintenance EOL, their oldest runner will always be four or five years old.  And ruby versions are maintained for three and a quarter years.  So, {4,5} + 3 = {7,8}.  Viola.  It's just math.  😉
  * Worded differently: 2.5 was supported when Ubuntu 20.04 was released, but _not_ when Ubuntu 22.04 was released.  And using the "four EOL versions" rule, we'll drop 2.5 from the build at roughly the same time GitHub drops ubuntu-20.04.
